import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Header from "@/components/headers";
import UserProfileInitializer from '../components/UserProfileInitializer';
import { Toaster } from "@/components/ui/toaster";
import { CreditsProvider } from '@/hooks/use-credits';
import Link from 'next/link';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} signInUrl="/sign-in">
      <html lang="en">
        <head>
          <script
            async
            src="https://checkout.razorpay.com/v1/checkout.js"
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <CreditsProvider>
            <UserProfileInitializer />
            <div className="flex items-center justify-between px-4 py-2">
              <Link href="/" className="flex items-center space-x-2">
                <span className="font-bold text-xl">Emoji Maker</span>
              </Link>
              <Header />
            </div>
            {children}
            <Toaster />
          </CreditsProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}